### ISSUE TITLE
[Question]: "How to define the most strict configuration possible for  Shellcheck  ?

### ISSUE THREAD

**Issue by Allan1901** [CICDToolbox/shellcheck#1]
### What is your question?

I’m collaborating in a opensource project :

https://bitbucket.org/AliasAPI/damnp/src/master/etc/shellcheck/run_shellcheck.sh

And i am finding trouble configuring Shellcheck  in the most sensitive way possible, so it would detected every generally undesired line of code. If anyone has any tips, it would be very welcome.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TGWolf** [comment]
Out of the box shellcheck will perform ALL checks, which is as secure as it can be. There is no additional configuration that you can add in order to extend it, the only thing you can do is turn off checks/features using the -e flag (which I can see you are already doing).

You could look at something like bats (https://github.com/sstephenson/bats) which might add a level of testing to the code but beyond that there isn't much else for static analysis for bash.

**Comment by TGWolf** [comment]
I would also recommend looking at another little tool/demo I wrote.

https://github.com/DevelopersToolbox/bash-snippets/blob/master/src/strict-mode/strict-mode.sh

This allows you to make sure your scripts are as strict as possible.
